name: Deploy to Linux
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Build distribution
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GCLOUD_PWD_TOKEN: ${{ secrets.GCLOUD_PWD_TOKEN }}
      run: cd Genesis ;  ./gradlew build ; ls build/distributions
    - name: Upload distribution
      run: ls -la ; mkdir .ssh ; echo ${{ secrets.DEPLOY_KEY }} > .ssh/id_rsa ; scp -B -v -o StrictHostKeyChecking=no Genesis/build/distributions/*.zip github@www.rpgframework.de:/var/www/html/genesis-builds/
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: www.rpgframework.de
        username: github
        key: ${{ secrets.DEPLOY_KEY }}
        source: "Genesis/build/distributions/*.zip"
        target: "/var/www/html/genesis-builds/"
